# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-node-browsers
      - image: circleci/postgres:9.6.9-alpine

    steps:
      - checkout

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip
            sudo docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
            sudo docker-php-ext-install pdo pdo_pgsql

      - run: sudo composer self-update

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # prepare the database
      - run:
          name: "Create Environment file and generate app key"
          command: |
            mv .env.testing .env
            php artisan key:generate

      - run:
          name: "Create database and run migration"
          command: |
            php artisan migrate: --env=testing
            php artisan db:seed

      - run:
          name: "Generate JWT encryption keys"
          command: php artisan jwt:secret

      # run tests with phpunit
      - run:
          name: "Run Tests"
          command: php vendor/bin/codecept run api
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output
